name: PhilStockWorld
favicon: null
layout_spectrum: 0.84518
typography_spectrum: 0.74027
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-6777740-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#dcdcdc'
    - '#042c46'
    - '#c27d22'
    - '#4c6876'
  brandStrength: 0.875
  lightness: 0.6875
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
